---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 512
    cpus: 4
platforms:
- name: ubuntu-12.04
  driver_config:
    box: precise64
    box_url: http://files.vagrantup.com/precise64.box
  run_list:
  - recipe[apt]
suites:
- name: package
  run_list:
  - recipe[selfsigned_certificate]
